version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pfm-backend
    volumes:
      - ./backend:/app
    ports:
      - "8005:8005"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/pfm_db
    depends_on:
      - mongo
    networks:
      - pfm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pfm-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8005
    depends_on:
      - backend
    networks:
      - pfm-network

  mongo:
    image: mongo:latest
    container_name: pfm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - pfm-network

volumes:
  mongo-data:


networks:
  pfm-network:
    driver: bridge
