services:
  - type: web
    name: pfm-backend
    runtime: docker
    region: singapore # best for India latency
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGODB_URL
        sync: false # User will input this in the dashboard
      - key: PORT
        value: 8005

  - type: web
    name: pfm-frontend
    env: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: pfm-backend
          property: host
